### ISSUE TITLE
Warning: D shaft from aliexpress link rattle around in bearings.

### ISSUE THREAD

**Issue by atoomnetmarc** [WINTFOX00/TRIDENT-STEPPER-DECOUPLER#4]
Hi, maybe I was unlucky, but the shafts from the Aliexpress link are too small. They rattle around in the bearings.

'2 Round D Shaft 55x5mm (longer still OK) | https://aliexpi.com/miUU'

All shafts are about 4.95mm or 4.96mm.
![afbeelding](https://github.com/WINTFOX00/TRIDENT-STEPPER-DECOUPLER/assets/48124268/48ea25dd-da95-4f9a-8a8b-0fa222252c46)

Bearing is 5mm.
![afbeelding](https://github.com/WINTFOX00/TRIDENT-STEPPER-DECOUPLER/assets/48124268/3cbba6e3-070e-4974-b95f-27a90fc2e987)

I had an old shaft laying around that measured 4.99mm and that fit just perfectly in the bearing. However, I had just 1 and it was too short.

Not really an issue for your awesome mod, just a warning for others to be aware.

**Comment by WINTFOX00** [comment]
Thank you for your reports. I'm on vacation so I'll check back in a few
days.
Btw, about the shaft, it's probably due to the (bad) quality fluctuations
from the manufacturer, the one I bought fits perfectly. You can fix it by
wrapping it in a few layers of kapton tape.


*HO HUYNH* | Freelancer Illustrator

----------------------------------------------

*https://www.artstation.com/fox* <https://www.artstation.com/fox>

**Comment by atoomnetmarc** [comment]
I have ordered 2 pieces of German made 5mm (DIN 175 specification) round 500mm long silver steel rods and have cut them to length. They are much more close to 5mm (4.98mm). I figured that D-shaft maybe not be the best solution under tension of the belts unless they are some kind of friction fit. Round shaft are not able to rattle.

Will let you know how this work out once I mounted them. Maybe I should cut a little flat spot for the grub screw of the pulleys if they slip.

![afbeelding](https://github.com/WINTFOX00/TRIDENT-STEPPER-DECOUPLER/assets/48124268/e477a6ca-e076-4762-a9d0-e911d37bb787)

**Comment by atoomnetmarc** [comment]
I have retried the assembly with the round 5mm shafts. They do not rattle. Time will tell if I need a flat spot for the pulleys.

I measured the noise (in peak dBA) of moving the printing head from left to right and back before the mod and after the mod. 
Subjective there is not much difference in noise level. I noticed that my printer has noise peaks at 25, 50 and 100 mm/s. 

According to my UNI-T UT353 dBA meter the average noise dropped a tiny bit from 48.5dBA to 47.3dBA.

Graph:

![afbeelding](https://github.com/WINTFOX00/TRIDENT-STEPPER-DECOUPLER/assets/48124268/5becdefc-1179-43a5-a261-73cae8c1799b)

For me this issue can be closed. Switching from Aliexpress d-shaft monday morning special to German made round shaft solved the rattle.

**Comment by WINTFOX00** [comment]
Hello. I just returned from vacation.
Thank you very much for the feedback. I will spend time improving and
fixing errors.
P/s: Regarding noise level, I don't have a specialized measuring device
yet, but with my printer using a 0.9 degree stepper, it almost makes the
printer silent, even with 8 microstepping + no stealthchop :D
Thank you again and have a nice day :D



*HO HUYNH* | Freelancer Illustrator

----------------------------------------------

*https://www.artstation.com/fox* <https://www.artstation.com/fox>
